/**
 * Recorded API responses from sub-issue decomposition smoke test.
 * Auto-generated — do not edit manually.
 * Re-generate by running: npx vitest run src/__test__/smoke-linear-api.test.ts
 * Last recorded: 2026-02-22T01:44:57.696Z
 */

export const RECORDED = {
  "teamStates": [
    {
      "id": "cf937197-a76e-4f36-9938-5013442f2137",
      "name": "Todo",
      "type": "unstarted"
    },
    {
      "id": "9e40430a-5404-4fed-be64-544417c7c46c",
      "name": "Duplicate",
      "type": "canceled"
    },
    {
      "id": "9bf913d6-f32d-452f-af43-3139cc8e5f3f",
      "name": "Canceled",
      "type": "canceled"
    },
    {
      "id": "7510263f-555b-42c4-98c3-f4196d755c4b",
      "name": "In Progress",
      "type": "started"
    },
    {
      "id": "6bcb2601-dc7b-487e-a407-416521aa235e",
      "name": "Backlog",
      "type": "backlog"
    },
    {
      "id": "69c39ddf-d135-47f7-8dbe-3fc6a539d504",
      "name": "Done",
      "type": "completed"
    },
    {
      "id": "2a4c7f41-80cd-4798-91e7-0aa6656d73ca",
      "name": "In Review",
      "type": "started"
    }
  ],
  "createParent": {
    "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
    "identifier": "UAT-255"
  },
  "createSubIssue1": {
    "id": "3294be2b-9d74-4b67-8c6d-544cd748e402",
    "identifier": "UAT-256"
  },
  "createSubIssue2": {
    "id": "96314b1b-3c82-448f-88ff-f6d14fa7ec8f",
    "identifier": "UAT-257"
  },
  "subIssue1Details": {
    "id": "3294be2b-9d74-4b67-8c6d-544cd748e402",
    "identifier": "UAT-256",
    "title": "[SMOKE TEST] Sub-Issue 1: Backend API",
    "description": "Implement the backend search API endpoint.\n\nGiven a search query, when the API is called, then matching results are returned.",
    "estimate": 2,
    "state": {
      "name": "Backlog",
      "type": "backlog"
    },
    "creator": {
      "name": "jason.barbee@calltelemetry.com",
      "email": "jason.barbee@calltelemetry.com"
    },
    "assignee": null,
    "labels": {
      "nodes": []
    },
    "team": {
      "id": "08cba264-d774-4afd-bc93-ee8213d12ef8",
      "name": "UAT",
      "issueEstimationType": "tShirt"
    },
    "comments": {
      "nodes": []
    },
    "project": null,
    "parent": {
      "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
      "identifier": "UAT-255"
    },
    "relations": {
      "nodes": []
    }
  },
  "subIssue2Details": {
    "id": "96314b1b-3c82-448f-88ff-f6d14fa7ec8f",
    "identifier": "UAT-257",
    "title": "[SMOKE TEST] Sub-Issue 2: Frontend UI",
    "description": "Build the frontend search UI component.\n\nGiven the search page loads, when the user types a query, then results display in real-time.",
    "estimate": 3,
    "state": {
      "name": "Backlog",
      "type": "backlog"
    },
    "creator": {
      "name": "jason.barbee@calltelemetry.com",
      "email": "jason.barbee@calltelemetry.com"
    },
    "assignee": null,
    "labels": {
      "nodes": []
    },
    "team": {
      "id": "08cba264-d774-4afd-bc93-ee8213d12ef8",
      "name": "UAT",
      "issueEstimationType": "tShirt"
    },
    "comments": {
      "nodes": []
    },
    "project": null,
    "parent": {
      "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
      "identifier": "UAT-255"
    },
    "relations": {
      "nodes": []
    }
  },
  "parentDetails": {
    "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
    "identifier": "UAT-255",
    "title": "[SMOKE TEST] Sub-Issue Parent: Search Feature",
    "description": "Auto-generated by smoke test to verify sub-issue decomposition.\n\nThis parent issue should have two sub-issues created under it.\n\nCreated: 2026-02-22T01:44:55.963Z",
    "estimate": null,
    "state": {
      "name": "Backlog",
      "type": "backlog"
    },
    "creator": {
      "name": "jason.barbee@calltelemetry.com",
      "email": "jason.barbee@calltelemetry.com"
    },
    "assignee": null,
    "labels": {
      "nodes": []
    },
    "team": {
      "id": "08cba264-d774-4afd-bc93-ee8213d12ef8",
      "name": "UAT",
      "issueEstimationType": "tShirt"
    },
    "comments": {
      "nodes": []
    },
    "project": null,
    "parent": null,
    "relations": {
      "nodes": []
    }
  },
  "createRelation": {
    "id": "2372db79-7760-41a6-bd55-cf753ad3d611"
  },
  "subIssue1WithRelation": {
    "id": "3294be2b-9d74-4b67-8c6d-544cd748e402",
    "identifier": "UAT-256",
    "title": "[SMOKE TEST] Sub-Issue 1: Backend API",
    "description": "Implement the backend search API endpoint.\n\nGiven a search query, when the API is called, then matching results are returned.",
    "estimate": 2,
    "state": {
      "name": "Backlog",
      "type": "backlog"
    },
    "creator": {
      "name": "jason.barbee@calltelemetry.com",
      "email": "jason.barbee@calltelemetry.com"
    },
    "assignee": null,
    "labels": {
      "nodes": []
    },
    "team": {
      "id": "08cba264-d774-4afd-bc93-ee8213d12ef8",
      "name": "UAT",
      "issueEstimationType": "tShirt"
    },
    "comments": {
      "nodes": []
    },
    "project": null,
    "parent": {
      "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
      "identifier": "UAT-255"
    },
    "relations": {
      "nodes": [
        {
          "type": "blocks",
          "relatedIssue": {
            "id": "96314b1b-3c82-448f-88ff-f6d14fa7ec8f",
            "identifier": "UAT-257",
            "title": "[SMOKE TEST] Sub-Issue 2: Frontend UI"
          }
        }
      ]
    }
  },
  "subIssue2WithRelation": {
    "id": "96314b1b-3c82-448f-88ff-f6d14fa7ec8f",
    "identifier": "UAT-257",
    "title": "[SMOKE TEST] Sub-Issue 2: Frontend UI",
    "description": "Build the frontend search UI component.\n\nGiven the search page loads, when the user types a query, then results display in real-time.",
    "estimate": 3,
    "state": {
      "name": "Backlog",
      "type": "backlog"
    },
    "creator": {
      "name": "jason.barbee@calltelemetry.com",
      "email": "jason.barbee@calltelemetry.com"
    },
    "assignee": null,
    "labels": {
      "nodes": []
    },
    "team": {
      "id": "08cba264-d774-4afd-bc93-ee8213d12ef8",
      "name": "UAT",
      "issueEstimationType": "tShirt"
    },
    "comments": {
      "nodes": []
    },
    "project": null,
    "parent": {
      "id": "e716d2c8-7711-4cc8-868b-711127b4eb94",
      "identifier": "UAT-255"
    },
    "relations": {
      "nodes": []
    }
  }
};
